version: '3.8'
services:
  app:
    image: recomenda-livros:latest  # Substitua pelo nome da sua imagem do Spring Boot
    container_name: recomenda-livros-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge